Dz feat progress bar
se348/DataZone-Angular-Client pull request #15
Opened 2024-01-10 18:10 UTC by yosephhabtamu

2024-01-11 12:08 UTC, destifo requested changes
address the comment

2024-01-11 12:08 UTC, destifo commented on src/app/shared/shared-directives/button-interaction.directive.spec.ts
> +//     expect(directive).toBeTruthy();
why is it commented?

2024-01-12 11:37 UTC, yosephhabtamu commented on src/app/shared/shared-directives/button-interaction.directive.spec.ts
> +//     expect(directive).toBeTruthy();
It was some test for the directive. The directive is not working so I removed both (the directive and test ofcourse)

2024-01-12 11:58 UTC, destifo commented on src/app/shared/shared-directives/button-interaction.directive.spec.ts
> +//     expect(directive).toBeTruthy();
ok.

2024-01-12 11:58 UTC, destifo approved these changes

2024-01-12 11:59 UTC, merged